### ISSUE TITLE
@vue/apollo-composable currently only works with @vue/composition-api <= 0.5.0

### ISSUE THREAD

**Issue by sadjow** [vuejs/vue-apollo#1009]
**Describe the bug**
I was trying to follow the setup instruction and I noticed that the last release from @vue/apollo-composable was 3 months ago. When trying to use it it was impossible to use the composition function. it was not returning anything neither any error.

**To Reproduce**
1. Follow the @vue/apollo-composable setup instruction(using latest version)
2. try to use a query
3. nothing will happen

**Expected behavior**
The graphql query should be executed.

**Versions**
vue:  2.6.11
vue-apollo: 3.0.3
apollo-client: 2.6.10
@vue/apollo-composable: 4.0.0-alpha.8 

@vue/composition-api: 1.0.0-beta.1 (latest, do not work)
@vue/composition-api: >= 0.6.x (do not work)
@vue/composition-api: <= 0.5.x (works, no bug)

**Additional context**
No error is triggered, it just does not execute the query.

**Comment by plmercereau** [comment]
Exact same problem here, downgraded to `@vue/composition-api@0.5.0` for now :/

**Comment by Qubeo** [comment]
I think #1000 should be fixing this, but not accepted yet :/

**Comment by Loremaster** [comment]
Confirm. It's an issue.

**Comment by DarkLite1** [comment]
I'm so glad I found this workaround. Lost a [whole day](https://stackoverflow.com/questions/62877027/vue-apollo-4-not-returning-graphql-query-results/62889474#62889474) on tinkering with my setup thinking it was me.

**Comment by tcastelly** [comment]
Thanks for the workaround, downgrade  `@vue/composition-api` has some side effects, but it's warning ... it should be OK.

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in data(): "TypeError: Cannot convert undefined or null to object"

```

**Comment by kahirokunn** [comment]
This pull request is awesome!
I need it!

**Comment by heavenkiller2018** [comment]
Exact same problem here,

**Comment by sadjow** [comment]
I am closing this issue because I just verified that the latest version of `@vue/apollo-composable` `4.0.0-alpha.10` with the latest version of `@vue/composition-api` `1.0.0-beta.6` is working nicely. So, this bug is not happening anymore.
