### ISSUE TITLE
Reactive Subscription creation failing - Getting "Invariant Violation: Must contain a query definition." Error

### ISSUE THREAD

**Issue by cryptowhaler** [vuejs/vue-apollo#1010]
Hi,
We are creating a Trading platform which should switch its data subscriptions to new market as selected by the user. The GraphQL request is working great but I am not able to create reactive subscriptions. Most of the content i found trying to get to the solution refers to query/mutations. Is there something i am doing wrong here?

Subscription Query -
![image](https://user-images.githubusercontent.com/53361416/86753506-bf2b5100-c05d-11ea-866b-f8ee218913e8.png)

Apollo -
![image](https://user-images.githubusercontent.com/53361416/86753978-22b57e80-c05e-11ea-885f-15d9ac7d3fda.png)

Error - 
![image](https://user-images.githubusercontent.com/53361416/86753732-f00b8600-c05d-11ea-8e30-e9c630cbb59d.png)

**Comment by cryptowhaler** [comment]
Found the solution.

**Comment by rebz** [comment]
@cryptowhaler what was your solution? Having the same problem.

**Comment by cryptowhaler** [comment]
The query name should be the same as the actual query. Attaching an example
here for your reference!


[image: Screen Shot 2020-10-23 at 8.04.13 PM.png]
