### ISSUE TITLE
Support Apollo 3

### ISSUE THREAD

**Issue by ais-one** [vuejs/vue-apollo#1015]
**Is your feature request related to a problem? Please describe.**
Apollo client is now at version 3.0

**Describe the solution you'd like**
We should start supporting version 3.0

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by SuddenlyRust** [comment]
Is there an estimated date when Apollo 3 will be supported @Akryum? 

I can understand that everything is in full swing for the official release of Vue 3 but to know the current status of this project would be very helpful 🙇‍♂️

**Comment by angad777** [comment]
> Is there an estimated date when Apollo 3 will be supported @Akryum?
> 
> I can understand that everything is in full swing for the official release of Vue 3 but to know the current status of this project would be very helpful 🙇‍♂️

Agreed. Any ETA's to support version 3 ? Would be nice if you could provide a high level estimate @Akryum

**Comment by the-jackalope** [comment]
Looks like #1031 is a candidate for Apollo 3 support!

**Comment by Akryum** [comment]
See https://github.com/vuejs/vue-apollo/issues/1011#issuecomment-710942324
