### ISSUE TITLE
Http Headers for individual querys?

### ISSUE THREAD

**Issue by Pblfer** [vuejs/vue-apollo#1019]
I want to use http headers, actually is reference about use and set up over the vue-apollo.js file with httpLinkOptions. but is possible to use different header in an individual query?

**Comment by Akryum** [comment]
Use the context system.
https://www.apollographql.com/docs/link/links/http/#passing-context-per-query

For example:

```js
export default {
  apollo: {
    myQuery () {
      return {
        query: gql`...`,
        context: {
          headers: { foo: this.fooHeader }
        }
      }
    }
  }
}
```
