### ISSUE TITLE
v4: ComputedRef does not exist in vue-demi (or composition api)

### ISSUE THREAD

**Issue by MechJosh0** [vuejs/vue-apollo#1021]
**Description**
Starting up the latest version displays the following error in the terminal.

**Version**
v4.0.0-alpha.10

**Error**

``` bash
ERROR in /node_modules/@vue/apollo-composable/dist/useLoading.d.ts(1,63):
1:63 Namespace '"/node_modules/vue-demi/lib/index"' has no exported member 'ComputedRef'.
  > 1 | export declare function useQueryLoading(): import("vue-demi").ComputedRef<boolean>;
      |                                                               ^
    2 | export declare function useMutationLoading(): import("vue-demi").ComputedRef<boolean>;
    3 | export declare function useSubscriptionLoading(): import("vue-demi").ComputedRef<boolean>;
    4 | export declare function useGlobalQueryLoading(): import("vue-demi").ComputedRef<boolean>;
```

**Comment by Akryum** [comment]
Could you try alpha 9 please? 🙏

**Comment by MechJosh0** [comment]
Same error but with composition api. I did search for that type to see where it should be coming from but was unsuccessful.

I am wondering if it should just be Ref and perhaps ComputedRef was deprecated during development.

**Comment by quentinus95** [comment]
Same issue here :hand:

**Comment by karladler** [comment]
any solution on this?

**Comment by karladler** [comment]
walking trough the migration guide solved it for me. ensure to import everything from core.
`import { ApolloClient } from '@apollo/client/core';`
https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/

**Comment by Akryum** [comment]
Still happening?

**Comment by MechJosh0** [comment]
@Akryum Still occurring in `@vue/apollo-composable v4.0.0-alpha.12` with `@apollo/client v3.2.5`.

I've tried following @karladler recommendation of using `@apollo/client v3` and following the migration updates, however, this hasn't resolved the issue. I'm unsure the connection on this either as it's a `vue-demi` import type error rather than anything related to `@apollo/client`, or I'm missing something.

**Comment by MechJosh0** [comment]
I've upgraded `@vue/composition-api v0.5.0` to `@vue/composition-api v1.0.0-beta.18` and these type errors have now gone away.

There was a bug in vue-apollo preventing me from upgrading composition-api but that has since been resolved.
