### ISSUE TITLE
[apollo-composable]  Multiple ApolloClients don't work

### ISSUE THREAD

**Issue by liaoliaojun** [vuejs/vue-apollo#1023]
**Describe the bug**
`resolveClient `  should has argument `clientId` #906

function resolveClient code:
```
function resolveClient() {
    if (clientId) {
      resolveClientWithId(providedApolloClients, clientId)
    }
    return resolveDefaultClient(providedApolloClients, providedApolloClient)
 }
```

useQuery.ts: 
```
 const { resolveClient } = useApolloClient()
 const client = resolveClient(currentOptions.value.clientId)
```
 

**To Reproduce**
Use `apollo-composable`  provide Multiple ApolloClients.

**Expected behavior**
work

**Versions**
@vue/composition-api：1.0.0-beta.6
@vue/apollo-composable：v4.0.0-alpha.10
@apollo-boost：0.4.7

**Additional context**

**Comment by nicolaiunrein** [comment]
Same issue here. Seems that using anything but the default client breaks.

**Comment by AntonnyAGS** [comment]
Any update about it? Same issue here

**Comment by jakedohm** [comment]
@Akryum I'm hitting this exact issue, where specifying `clientId` doesn't do anything. I'm updated to the latest versions, I believe, has this fix been released yet? If not, would it be possible to include it in a release/patch soon, or let me know how to update my project to get this fix.

Thanks!

PS: Amazing work on this, it's SOO good to work with ❤️
