### ISSUE TITLE
use vue-cli devProxy target domain request fetch :method to GET

### ISSUE THREAD

**Issue by nshusr** [vuejs/vue-apollo#1034]
**Describe the bug**
set vue-cli devProxy target domain request fetch :method to GET
result error

**To Reproduce**
set vue.config.js add
```
  devServer: {
    proxy: {
      '^/api/graphql': {
        target: website domain online,
        changeOrigin: false,
        secure: false,
        ws: true,
        pathRewrite: {
          '^/api/graphql': ''
        }
      }
    }
```
![image](https://user-images.githubusercontent.com/45023042/89550016-ad46f480-d83b-11ea-9425-63ff268a5bad.png)

**Expected behavior**
success request data

**Versions**
vue: 2.6.11
vue-apollo:3.0.3
apollo-client:2.6.10

**Comment by Akryum** [comment]
Why do you want to move to HTTP GET?

**Comment by nshusr** [comment]
@Akryum thank you, my problem solved
