### ISSUE TITLE
On refetch, result gets out of sync

### ISSUE THREAD

**Issue by jacenre** [vuejs/vue-apollo#1038]
**Describe the bug**
On initial request, the request is fine, but on refetch the result is undefined.
This is likely because on refetch an `isTrusted` is passed with query parameters (not by me, but apollo itself), while this is not passed on during the initial request. Thus useQuery is directed to a different part of the cache than the updated request, and it falls back on the default value.

**To Reproduce**
1. Write a request. For instance, 
```
const GET_INSTITUTE_CASE_DETAILS_QUERY = gql`
  query getInstitudeCaseDetails($id: ID!) {
    instituteCase(id: $id) {
      id
      name
    }
  }
`;

const { result, refetch } = useQuery(
  GET_INSTITUTE_CASE_DETAILS_QUERY,
  { id },
);
const instituteCase = useResult(result, null, (data) => data.instituteCase);
```
2. Result is not null. The query variables that are sent by apollo were:
![image](https://user-images.githubusercontent.com/30551812/89777932-eb2e6c00-db0c-11ea-9a6b-d3f255514945.png)
3. Run `refetch()`.
4. Request is successful (looking at network tab), but result is empty. The query variables that are sent by apollo were:
![image](https://user-images.githubusercontent.com/30551812/89778011-0d27ee80-db0d-11ea-9022-f1c6e65d5736.png)

**Expected behavior**
Refetched data to be in result, but it is undefined.

**Versions**
vue: 2.6.11
vue-apollo: 4.0.0-alpha.7
apollo-client: 2.6.8

**Additional context**
In the loading state while refetching, the result is looking at the original cache of the initial request, and the result then contains the data of the initial request that did work.
So in between step 3 and 4, the loading state shows the result of the initial request, which was correct.

This bug also happens when loadMore is used.

**Comment by martijnimhoff** [comment]
I'm having the same problem.

**Comment by jacenre** [comment]
This problem was solved by a very unrelated issue than vue-apollo or apollo in general.

**Comment by rebz** [comment]
@jacenre - Do you recall how you solved the issue? Running into the same thing where all my variables are replaced with `isTrusted: true`.
