### ISSUE TITLE
onServerPrefetch does not exist in Vue 3

### ISSUE THREAD

**Issue by reegodev** [vuejs/vue-apollo#1042]
**Describe the bug**
The `onServerPrefetch` lifecycle hook does not exist anymore in Vue 3

**To Reproduce**
1. Setup a Vue 3 project
2. Install Vue Apollo
3. Install @vue/apollo-composable
4. Perform a query using `useQuery`
5. In console you should see the error `TypeError: vue_demi_1.onServerPrefetch is not a function`

**Versions**
vue: 3
vue-apollo: 4.0.0-alpha.10
apollo-client: 2.6.10

**Comment by parion** [comment]
While some outstanding patch PRs are awaiting fixes and reviews, the following patch should help:
https://github.com/vuejs/vue-apollo/issues/1011#issuecomment-679298995

**Comment by wobsoriano** [comment]
Works now

```html
<script setup lang="ts">
import { onServerPrefetch, ref } from 'vue'

const todo = ref()

onServerPrefetch(async() => {
  const resp = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const data = await resp.json()
  todo.value = data
})
</script>
```
