### ISSUE TITLE
Type 'void' is not assignable to type 'object'.

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vue-apollo#1051]
**Describe the bug**

There might be an issue with the function `useResult` within `@vue/apollo-composable` or I'm doing something wrong. 

```html
<template>
    <h2 v-if="loading">Loading...</h2>
    <div v-else>
      <div v-for="account in allAccounts" :key="account.accountIdentifier"> {{ account.name }} </div>
    </div>
</template>
```
The code below works fine but throws the error: for the part `allAccounts`in the section `<template>`:
> Type 'void' is not assignable to type 'object'.

![image](https://user-images.githubusercontent.com/10828570/91415669-ae71ad00-e84e-11ea-91f6-15c8d21bb6df.png)

```typescript
<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import { useResult } from '@vue/apollo-composable'
import { useAllAccountsQuery } from 'src/graphql/generated/operations'

export default defineComponent({
  setup() {
    const { result, loading } = useAllAccountsQuery()
    const allAccounts = useResult(result)

    return { allAccounts, loading }
  },
})
</script>
```
When trying to solve it by using n empty object like this:
```typescript
const { result, loading } = useAllAccountsQuery()
const allAccounts = useResult(result, {})
```

We get this error:
> Object is possibly 'undefined'.Vetur(2532)

![image](https://user-images.githubusercontent.com/10828570/91415839-e11ba580-e84e-11ea-8578-1f323be5b646.png)

The only workaround to avoid the error in the Vue `<template>` is this:
```typescript
const { result, loading, error } = useAllAccountsQuery()
const allAccounts = useResult(result, [])
```
But  than the type reverts to `any` which is not desirable. 

On a side note, there are no TS errors in the script section:
```typescript
const { result, loading, error } = useAllAccountsQuery()
const allAccounts = useResult(result)

if (allAccounts.value) {
   allAccounts.value.accounts
   allAccounts.value.accounts[0].accountIdentifier
}
```

What are we doing wrong?

**Expected behavior**
We expected no Vetur error and intellisense to work.

**Versions**
```
 "dependencies": {
    "@vue/apollo-composable": "^4.0.0-alpha.10",
    "@vue/composition-api": "1.0.0-beta.11",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
    "apollo-link-http": "^1.5.17",
    "graphql": "^15.3.0",
  },
```

**Additional context**

Possible related issue [here](https://github.com/dotansimha/graphql-code-generator/issues/4653) and PR [here](https://github.com/vuejs/vue-apollo/pull/872).

**Comment by Akryum** [comment]
Could you check if it's fixed?

**Comment by DarkLite1** [comment]
Thank you for getting back to me. Looking back at the code above I did this:

```typescript
    const { result, loading } = useAllAccountsQuery()
    const allAccounts = useResult(result)
```

While it is fixed now by picking the correct property, like so:
```typescript
    const { result, loading, error } = useAllAccountsQuery()
    const allAccounts = useResult(result, null, (data) => data.accounts)
```

Which then translates to a correctly usable and typescript supported template:
```
    <h2 v-if="loading">Loading...</h2>
    <div v-else-if="error">Error: {{ error.message }}</div>
    <div v-else-if="allAccounts">
      <div v-for="account in allAccounts" :key="account.accountIdentifier">
        {{ account.name }}
        {{ account.accountIdentifier }}
      </div>
    </div>
````

Sorry for all the confusion, still learning. Closing this one as user problem :)
