### ISSUE TITLE
Streamline useQuery with useMutation

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vue-apollo#1065]
**Is your feature request related to a problem? Please describe.**
As a newbie to web development I found myself in the situation where I had to execute a query but only when a specific condition was met. Doing this with `useMutation` is really easy as it returns a function that can be called upon later to execute the mutation. However, the same cannot be said for `useQuery`. 

Asking this question on [StackOverflow](https://stackoverflow.com/questions/64138894/how-to-trigger-a-graphql-query-when-a-ref-changes-with-the-vue-composition-api) returned an answer where the person who responded proposed the code below which of course does not work:

```typescript
export default defineComponent({
  setup() {
    const { result, loading, error, call } = useViewerQuery()
    watchEffect(async () => {
      if (isAuthenticated.value) {
          await call()
      }
    })

    return {
      isAuthenticated,
      loading,
      error
    }
  }
})
```

**Describe the solution you'd like**
It would be great if `useQuery` could be used in the same way as [useMutation](https://www.apollographql.com/docs/react/data/mutations/) :

```
When your component renders, useMutation returns a tuple that includes:
- A mutate function that you can call at any time to execute the mutation
```

**Describe alternatives you've considered**
The only workaround I found was to set the [option](https://v4.apollo.vuejs.org/guide-composable/query.html#options) for `useQuery` to `enabled: false`.

**Comment by Akryum** [comment]
`useQuery` is meant for reactive state and declarative querying. Use the `enabled` option to disable or re-enable the query wich will automatically make network requests if necessary (`useQuery` options can be reactive).

**Comment by DarkLite1** [comment]
Thank you for the feedback. Can I ask you a related question? How does this translate to `useResult`? The [docs](https://v4.apollo.vuejs.org/guide-composable/query.html#result-picking) say one can select a nested property with `useResult` quite easiy. 

```typescript
// You don't need to do this!
const messages = useResult(result, null, data => data && data.currentUser && data.currentUser.messages)

// Instead do this:
const messages = useResult(result, null, data => data.currentUser.messages)
```

This seems to be very hard when we are watching for the result to change and only then use `useResult`. The only thing we're trying to do is check if the property `preference` is `null || underlined` on the returned `result` and if it is run a mutation to set them.. 

```typescript
export default defineComponent({
  setup() {
    const { result, loading, error } = useViewerQuery(() => ({
      enabled: isAuthenticated.value,
    }))

    const {
      mutate: setPreferenceDefault,  loading: setPreferenceDefaultLoading, error: setPreferenceDefaultError, onDone,  } = useSetPreferenceDefaultMutation({
      variables: {
        language: 'en-us',
        darkMode: false,
      },
    })
    watchEffect(() => {
         if (!result.value && !result.value.preference.value.) {
          console.log('MainLayout set default preference')
          void setPreferenceDefault()
      }
    })
  },
})
```

This could be more of TypeScript question, because accessing `result.value.preference.value.` seems to be not accepted. We've tried with [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) but no luck yet. We were just thinking that `useResult` would simplify the checken of this nested property:

```
query viewer {
  viewer {
    preference {
      language
      darkMode
    }
  }
}
```

**Comment by DarkLite1** [comment]
I think there's a small issue with this approach. When setting the option `enabled` of the query it seems that the `watchEffect` function is triggered **before** the `useViewerQuery` is triggered.

A small example on this is below. We first try to retrieve the preferences with the query `useViewerPreferencQuery` and afterwards, when there are no preferences, we try to set them with the mutation `useSetPreferenceMutation`.. 

This approach is flawed because in the Network log we can see the `useSetPreferenceMutation` being called first and only then the `useViewerPreferencQuery`.

```typescript
import { defineComponent, watchEffect } from '@vue/composition-api'
import { isAuthenticated } from 'src/store/authStore'
import {
  useSetPreferenceDefaultMutation,
  useViewerQuery,
} from 'src/graphql/generated/operations'

export default defineComponent({
  setup(_, { root }) {
    const { result, loading, error } = useViewerQuery(() => ({
      enabled: isAuthenticated.value,
    }))

    const {
      mutate: setPreferenceDefault,
      loading: setPreferenceDefaultLoading,
      error: setPreferenceDefaultError,
      onDone,
    } = useSetPreferenceDefaultMutation({
      variables: {
        language: 'en-us',
      },
    })

    watchEffect(() => {
      if (
        isAuthenticated.value &&
        !loading.value &&
        !setPreferenceDefaultLoading.value &&
        !result.value?.viewer?.preference
      ) {
        void setPreferenceDefault()
      }
    })

    return {
      isAuthenticated,
      loading: loading || setPreferenceDefaultLoading,
      error: error || setPreferenceDefaultError,
    }
  },
})
````

I  know I'm a bit of a noob on this but can you please have another look if this is the desired behavior? Or that I am not doing it right.
