### ISSUE TITLE
Fetching single item from cache when cache is filled with array

### ISSUE THREAD

**Issue by RubenVanEldik** [vuejs/vue-apollo#1075]
Sorry to create an issue in the main repository, but I couldn't find anything online and didn't receive an answer on the nuxt-apollo discord server.

Is it possible to fetch a singular item from the Apollo cache after I've fetched multiple items on another page?

I have already fetched `stories` on another page, but now I want to fetch a singular item `story(id: $id)` from the cache. So this is a `fetchPolicy: 'cache-only'` query. I have tried a few things, but it looks like Apollo does not know that `stories` is the plural of `story` (which makes sense). Is there anything I can add to let Apollo know that if I ask for a story it can also return the stories item with the same ID?

Would this for example work with something like the IntrospectionFragmentMatcher?

This is quite essential to a project I am working on. If anybody could point me in the right direction I would be eternally grateful!

**Comment by codejie** [comment]
I have the same issue.
