### ISSUE TITLE
type errors in useQuery and useLazyQuery

### ISSUE THREAD

**Issue by schTi** [vuejs/vue-apollo#1078]
**Describe the bug**
There are multiple type errors in useQuery and useLazyQuery. useLazyQuery has a type error in the `fetchMore` type declaration. Additionally the `enabled` field of useQuery should be a `Ref<boolean>`, but is only declared as `boolean`

**Versions**
vue-apollo-composable 4.0.0-alpha.12

**Comment by Akryum** [comment]
Please provide more info and a reproduction thanks.
