### ISSUE TITLE
TypeError: root is undefined from V4 Composition API

### ISSUE THREAD

**Issue by Moodycomputer** [vuejs/vue-apollo#1080]
**Describe the bug**
I'm using the V4 Composition API with Vue 3 and seeing a series of errors when I attempt to use `useQuery` in the `setup()` of a component.

<img width="832" alt="Screen Shot 2020-10-19 at 5 14 22 PM" src="https://user-images.githubusercontent.com/1408862/96512485-8db24c00-122e-11eb-86a1-0d58f32e54ee.png">

**To Reproduce**
Relevant files:

``` js
// main.js

import { createApp } from 'vue'
import router from "./router"
import App from './App.vue'
import { DefaultApolloClient } from '@vue/apollo-composable'
import apolloClient from '@/apollo'

const app = createApp(App)
app.use(router)
app.provide(DefaultApolloClient, apolloClient)
app.mount('#app')
```

``` js
// apollo.js

import ApolloClient from 'apollo-boost'

const apolloClient = new ApolloClient({
  uri: 'http://localhost:3000/api'
})

export default apolloClient
```

``` js
// Home.vue

<template>
  ...
</template>
<script>
import { useQuery } from '@vue/apollo-composable'
import gql from 'graphql-tag'

export default {
  name: 'Home',
  setup(){
    const { result } = useQuery(gql`{ QUERY }`)
    return {
      result
    }
  },

}
</script>

```

**Expected behavior**
Expect `useQuery` to behave as described

**Versions**
vue: 3.0.0-0
apollo-composable: 4.0.0-alpha.10
apollo-boost: 0.4.9

**Comment by Akryum** [comment]
Could you please try with the latest versions? Ty

**Comment by Moodycomputer** [comment]
@Akryum Well wouldn't you know that fixed it.

Thank you so much!
