### ISSUE TITLE
The "main" bundle of v4 is in AMD format

### ISSUE THREAD

**Issue by equinox7** [vuejs/vue-apollo#1081]
**Describe the bug**
The "main" bundle of v4 is in AMD format. Is it intended? It used to be commonjs, and it seems it was changed in https://github.com/vuejs/vue-apollo/commit/cfbb9da5af00336e56a09da73a4760ba0dbf5874.

So now bundle contains code like:
```js
define("useApolloClient", ["require", "exports", "vue-demi"], function (require, exports, vue_demi_1) {
```

And I keep getting `ReferenceError: define is not defined`. I am using webpack 4 to build my app.

**Expected behavior**
The bundle should be in commonjs format.

**Versions**
apollo-client: 4.0.0-alpha.12

**Additional context**
If this was intended, can you please explain the reasons behind this decision?

**Comment by Akryum** [comment]
Webpack should use the ESM version. 🤷

**Comment by equinox7** [comment]
On the server bundle it tries to use the one from "main" in `package.json`, which is AMD. Before it was working with commonjs.

**Comment by jsbroks** [comment]
@Akryum Same issue here. After upgrading to `alpha-12` I am getting the same error in my nuxtjs application.

I fixed it by downgrading with (`alpha-11` game me the same issue):

`yarn add @vue/apollo-composable@4.0.0-alpha.10`

**Comment by devCrossNet** [comment]
Hey @Akryum,
thanks for the great work!
Do you know a workaround? I need a version above alpha.10 because I have to use multiple apollo-clients and I am a little bit in a hurry 😭

**Comment by JoeSchr** [comment]
I get the same error using this with nuxt & typescript.

I just was trying to do import `DefaultApolloClient` symbol:
```ts
import { DefaultApolloClient } from "@vue/apollo-composable";
```

This is definitely suddenly broken. Is there any reason for the switch to "amd"?

Nuxt version:
```json
    "nuxt": "2.14.7",
```

**Comment by JoeSchr** [comment]
@devCrossNet 
> Do you know a workaround? I need a version above alpha.10 because I have to use multiple apollo-clients and I am a little bit in a hurry
I cloned the branch in #1089 and then `yarn pack` it as tarball which I added to my git for now

how to build workspace package
```sh
cd packages/vue-apollo-composable
yarn build
yarn pack
mv vue-apollo-composable-v4.0.0-alpha.12.tgz $yourproject
cd $yourproject
npm install ./vue-apollo-composable-v4.0.0-alpha.12.tgz
```

**Comment by devCrossNet** [comment]
@JoeSchr I wasn't able to spend more time on it and decided to go back to the regular usage without the composition-api on pages where I need two clients. I am waiting for a new release of vue-apollo-composables, that hopefully will fix this issue and then do a refactoring.

**Comment by fedeee** [comment]
Same problem here folks, tried to upgrade but now jest is now throwing the error reported above:
`ReferenceError: define is not defined`
Whenever there is a component or file importing from `@vue/apollo-composable`.

**Comment by tcastelly** [comment]
Hello, I have the same problem. I'm using Vue 3 in ssr

**Comment by Mando75** [comment]
You can fix the errors in Jest by doing the following:

Change your `.babelrc` file to `babel.config.js` that `module.exports = ` your config. (see https://github.com/facebook/jest/issues/6229#issuecomment-392205646)

Add the following to your Jest config:
```javascript
  moduleNameMapper: {
    '@vue/apollo-composable': '@vue/apollo-composable/dist/index.js', // Override which bundle Jest imports from
  },
  // If you get `Unexpected token` on import/export, add this to transform the @vue/apollo-composable bundle
  transformIgnorePatterns: ['/node_modules/(?!@vue/apollo-composable).+\\.js$'], 
```
See https://github.com/facebook/jest/issues/6229#issuecomment-403539460

**Comment by leo91000** [comment]
Is there any workarround for nuxt ?

**Comment by Mando75** [comment]
> Is there any workarround for nuxt ?

The workaround I posted above works in my Nuxt project using the Apollo module.

**Comment by Kauto** [comment]
@leo91000 
I found a two step solution for nuxt:
1) add the transpiling of `@vue/apollo-composable` to `nuxt.config.js`
```
{
....
  build: {
    transpile: [
      '@vue/apollo-composable'
    ],
   }
 }
```

2) import all components directly from `@vue/apollo-composable/dist` instead of only `@vue/apollo-composable`. For example:
```
import { useResult } from '@vue/apollo-composable/dist'
```

Works with the newest version. No need to revert back to alpha10.

**Comment by tcastelly** [comment]
Is there any workaround for Webpack? :)

**Comment by MisaelMa** [comment]
I changed in the tsconfig

"module": "esnext"
to
"module": "commonjs"

with that the problem was solved for me

**Comment by devCrossNet** [comment]
@JoeSchr I found a workaround: vuesion/vuesion#552.
- working example with SSR: https://github.com/vuesion/vuesion/blob/next/src/pages/example/apollo.vue
- example test: https://github.com/vuesion/vuesion/blob/next/src/pages/example/apollo.spec.ts

**Comment by stephane303** [comment]
I tried all the above solutions, none of them worked in my case. I am using Vue2, Vuetify and @vue/apollo-composable@4.0.0-alpha.12.
I tried to downgrade to  @vue/apollo-composable@4.0.0-alpha.10, with no success.

**Comment by Akryum** [comment]
The build process has been changed and will be released in alpha.13
