### ISSUE TITLE
Vue-apollo 4 does not properly fetch data with chrome

### ISSUE THREAD

**Issue by edarblanco** [vuejs/vue-apollo#1096]
Following the steps described in the official documentation to use `vue-apollo 4` and the composition `API of vue 3`, everything works fine when I `Firefox` but it does not happen when I use `Chrome`, in `Chrome`, I get an error like this fetch error,
[![chrome-network-tab][1]][1]

both when making queries and mutations, but in `Firefox`, all the responses are obtained correctly as seen in the network tabs `Firefox` response network tab:
[![firefow-network-tab][2]][2]

and `Chrome` response network tab:
[![chrome-response-network-tab][3]][3]

Expected behaviour: Full response in `Chrome` as the result in `Firefox`
Resulting behaviour: Failed to get data on `Chrome` (empty network tab) 

To try a little more, I have followed the example of Natalia Tepluhina described here https://dev.to/n_tepluhina/vue-apollo-v4-the-first-look-c32 and tested in both browsers, `Chrome/Chromium` and also `Firefox` and the result is the same in `Firefox` it works but not in `Chrome`

Try in older projects with older versions of `vue` and `vue-apollo` with the same result, error in `Chrome`

```
Chrome version:  86.0.4240.111 (x86_64)
Mozilla Firefox: version 82.0 (x86_64)
```

  [1]: https://i.stack.imgur.com/hZnQm.png
  [2]: https://i.stack.imgur.com/Pfl98.png
  [3]: https://i.stack.imgur.com/nmTzn.png

**Comment by Akryum** [comment]
Please try with all extensions disabled.

**Comment by edarblanco** [comment]
@Akryum Thanks for that, after disabling the extensions it works
