### ISSUE TITLE
Heuristic fragment warning despite fragmentMatcher in client

### ISSUE THREAD

**Issue by yaki4** [vuejs/vue-apollo#1101]
I've got a heuristic fragment warning on a query with union.
In my apollo config, my client is set with an IntrospectionFragmentMatcher with a correct schema but the warning pop anyway.

my config: 
<img width="642" alt="Capture d’écran, le 2020-11-17 à 23 26 21" src="https://user-images.githubusercontent.com/1856630/99483490-5073d380-292c-11eb-8f93-0162ad38c3cd.png">

the faulty query
<img width="512" alt="Capture d’écran, le 2020-11-17 à 23 26 59" src="https://user-images.githubusercontent.com/1856630/99483530-671a2a80-292c-11eb-93ee-1263b46b2c5c.png">

As you can see this union is on my schema.
<img width="395" alt="Capture d’écran, le 2020-11-17 à 23 27 22" src="https://user-images.githubusercontent.com/1856630/99483557-7305ec80-292c-11eb-9cdf-19614570df48.png">

<img width="995" alt="Capture d’écran, le 2020-11-17 à 23 29 10" src="https://user-images.githubusercontent.com/1856630/99483682-bc563c00-292c-11eb-81bc-72f085cd940a.png">

**Expected behavior**

**Versions**
vue: 2.6.12
vue-apollo: 3.0.4
apollo-client: 2.6.4

**Comment by paulpdaniels** [comment]
The key for `InMemoryCache` is called `fragmentMatcher`, but you are calling it `fragmentMatcherV2` so it won't get picked up by the `Cache` and so it is throwing that warning.

**Comment by dmitry** [comment]
@paulpdaniels is right, you have to replace to: `{ fragmentMatcher: fragmentMatcherV2 }`

**Comment by yaki4** [comment]
Oh god, it's so obvious now you said it. 
Many thanks for poiting that out.
