### ISSUE TITLE
Fix apollo-composable peer deps

### ISSUE THREAD

**Issue by lorensr** [vuejs/vue-apollo#1116]
**Describe the bug**

According to this: https://github.com/vuejs/vue-apollo/issues/1011#issuecomment-710942324

`@vue/apollo-composable` supports Vue 3. However, it still has a peer dep of Vue 2:

```
npm WARN @vue/apollo-composable@4.0.0-alpha.12 requires a peer of @vue/composition-api@^1.0.0-beta.16 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/apollo-composable@4.0.0-alpha.12 requires a peer of graphql@^14.5.8 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/apollo-composable@4.0.0-alpha.12 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
```

It also has a runtime error:

![image](https://user-images.githubusercontent.com/251288/102172367-9d34c680-3e66-11eb-9a82-fb006d6f5cf7.png)

And when I install the latest `@vue/composition-api`, it has Vue 2 as a peer dep and results in compile warnings and a different runtime error.

**Versions**
```json
  "dependencies": {
    "@apollo/client": "^3.3.6",
    "@vue/apollo-composable": "^4.0.0-alpha.12",
    "@vue/composition-api": "^1.0.0-beta.21",
    "core-js": "^3.6.5",
    "graphql": "^15.4.0",
    "vue": "^3.0.4"
  },
```

**Comment by lorensr** [comment]
Here's my repro, without `composition-api`. It's just a small attempt at getting vue@3 composition working:

https://github.com/GraphQLGuide/guide-vue/tree/repro-1116

**Comment by Akryum** [comment]
It seems like your packages are not installed properly, try removing `node_modules` and any lock file and install again.

**Comment by lorensr** [comment]
Thank you, you are correct!

**Comment by zdb999** [comment]
Hi, I'm having the exact same warnings, but deleting all the installed problem, but deleting the `yarn.lock` file and the `node_modules` folder and reinstalling does not fix the issue. What else should I try?

Here is my `package.json`.

```
{
  "name": "my-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@apollo/client": "^3.3.20",
    "@headlessui/vue": "^1.2.0-105068",
    "@heroicons/vue": "^1.0.1",
    "@vue/apollo-composable": "^4.0.0-alpha.12",
    "@vueuse/core": "^5.0.3",
    "@vueuse/head": "^0.6.0",
    "core-js": "^3.14.0",
    "graphql": "^15.5.1",
    "graphql-tag": "^2.12.5",
    "vue": "^3.0.5",
    "vue-i18n": "^9.1.6",
    "vue-router": "4",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.3.3",
    "@tailwindcss/line-clamp": "^0.2.1",
    "@tailwindcss/typography": "^0.4.1",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.6",
    "postcss": "^8.3.4",
    "tailwindcss": "^2.1.4",
    "typescript": "^4.3.2",
    "vite": "^2.3.7",
    "vue-tsc": "^0.0.24"
  }
}
```
