### ISSUE TITLE
Problem when using apollo client with vite 2

### ISSUE THREAD

**Issue by Rezvitsky** [vuejs/vue-apollo#1135]
Hello! It became necessary to use apollo-clinet (https://v4.apollo.vuejs.org/) with vite 2. When I installed all the packages and run the `npm run dev` project, the console gives the following errors:
![Screenshot_2](https://user-images.githubusercontent.com/24964186/106266594-3410e300-625b-11eb-83a9-f41a67ff41be.png)

**Comment by Akryum** [comment]
You need to import things from `@apollo/client/core` instead because for some reason the Apollo team decided to make the react version of Apollo Client the default entry point...

**Comment by Rezvitsky** [comment]
> You need to import things from `@apollo/client/core` instead because for some reason the Apollo team decided to make the react version of Apollo Client the default entry point...

Thanks, I understood, I hope in the future there will be a full-fledged graphql client for vue

**Comment by danieltf1** [comment]
@ennjoy hello, could you share the exact line you've changed please ?
