### ISSUE TITLE
How does one write unit tests for components using Vue-Apollo

### ISSUE THREAD

**Issue by JasonLi914** [vuejs/vue-apollo#286]
As the title suggests, does anyone have an example somewhere where they successfully mock out vue-apollo for unit tests?

**Comment by gmac** [comment]
Bump on this question. It would be really helpful to have some documented guidance on this. @JasonLi914 – did you figure out any solutions that you could report back here with?

**Comment by rkomiyama** [comment]
Also bumping this question. I'm not sure if there's a way to achieve 100% code coverage.

<img width="333" alt="screen shot 2018-08-20 at 3 03 39 pm" src="https://user-images.githubusercontent.com/347483/44360971-76c71200-a48a-11e8-9190-88695b1d4f1c.png">
