### ISSUE TITLE
Auth-Header not refreshing

### ISSUE THREAD

**Issue by RaphaelSchein** [vuejs/vue-apollo#370]
I have an GraphQL API serving every Information, the authentication is done with JWT Token in the header, the client (written with VUE) obtains the jwt from an seperated http-post endpoint and stores it in the localstorage, now i have the problem if the client logs in and stores the token in the localstorage its not used in the header of the apollo client. After the client reloads the site it worked but directly after login not.

**Comment by paulpdaniels** [comment]
You'll need to provide a bit more information to get support (also this doesn't sound like a vue-apollo issue it sounds like your apollo-link-context is not dynamically fetching the cookie per call). Also since this is primarily a bug channel you might be better off submitting this on SO.

**Comment by stefl** [comment]
There is an additional method that you need to hook into to called `onLogin`. This example has code that you should be able to use to achieve this: https://github.com/Akryum/vue-apollo/blob/master/tests/demo/src/components/UserLogin.vue

**Comment by rlfrahm** [comment]
Sorry to resurrect an extremely old issue, but it took me too long to find this answer... Not even realizing that the default `vue-apollo` file comes with `onLogin` and `onLogout` hooks. Is this documented somewhere, and if not, can we add it to help others? There are quite a few SO questions and issues that have been asked here around this.

**Comment by douglasg14b** [comment]
Yeah, searching the docs for `auth` brings up nothing, which definitely raises the question of how to ensure that the clients requests have the appropriate header, and how you can update that if it changes. Like with JWTs.
