### ISSUE TITLE
[Advice] How to build an autosave feature with vue-apollo?

### ISSUE THREAD

**Issue by JoeSchr** [vuejs/vue-apollo#502]
So I'm using vue-apollo and I try to build an autosave for my form and I need a way for the vue-apollo cache to don't overwrite newer data which already changed the app while saving. 

I will try to keep this short and concise. I already have a system in place that autosaves via a mutation whenever a change to my data occurs (via a deep watch and _.debounce timeout). 

What I have trouble with is, is this usecase: The users is in the process of writing eg. in a textfield and writes a longer text, making a thinking break, a debounce will be triggered and saves via mutation. Now the user starts writing again, here a race condition happens, because while the user is typing, the "old" save request comes back and apollo updates the cache with it. So what happens, the textfield will reset to the state when the autosave was send (the users paused) and will of course greatly frustrated the user because everything they wrote since then is lost.

Solutions I tried:
- decoupling the data from vue-apollo while editing (via a lazy setter/getter computional): this worked until I needed to make a component which should work on a many-to-many nested relationship. so whenever I created and then update/delete an item on this relationship, I would actually need the id (aka the data from the save request).

- setting a mutex on the beginning of keypressdown and not firing autosave until @input: this is very not-DRY (event handler on every child component) and also now all my child component need to know about this and fire up the input and change events so I can listend to them.

Help? Any suggestions, any ideas?

Also I'm happy to go into more detail. For example here is my debounce pseudo code:
```
  watch: {
    value: {
      deep: true,
      handler: _.debounce(function(val) {
        // get only changed fields
        let changed = difference(val, this.previous);

        // prepare changed and nested mutation for gql mutation
        // ...
        //
        this.previous = _.cloneDeep(val);
        return $apollo.mutate({  // update mutation});
      }, 500),
    },
```

**Comment by ydfzgyj** [comment]
I'm not sure I have completely understood what you mean, but I think in fact you need to write your data back to apollo cache after mutation is successful, so you can skip this step if you don't want the old data cover the new data? Your autosaved data only need to be read when user refresh the page.

**Comment by JoeSchr** [comment]
Closed because of inactivity
