### ISSUE TITLE
ApolloMutation renders children twice

### ISSUE THREAD

**Issue by lukasfrana** [vuejs/vue-apollo#507]
Hi,
I don't know if it's a vue-apollo issue or Vue issue, but everything I put in the ApolloMutation is being rendered twice. Little modified code from vue-apollo docs.
```vue
<ApolloMutation
  :mutation="gql"
  :variables="{values}"
  @done="onDone"
>
  <template slot-scope="{ mutate, loading, error }">
    <button
      class="button is-primary"
      :disabled="loading"
      @click="mutate()"
    >Save</button>

    <p v-if="error">{{ error }}</p>
  </template>
</ApolloMutation>
```
The button appears twice and the second button doesn't have access to scoped variables. So I have this temp fix.
```vue
<ApolloMutation
  :mutation="gql"
  :variables="{values}"
  @done="onDone"
>
  <template slot-scope="{ mutate, loading, error }">
    <button
      v-if="mutate !== undefined"
      class="button is-primary"
      :disabled="loading"
      @click="mutate()"
    >Save</button>

    <p v-if="error">{{ error }}</p>
  </template>
</ApolloMutation>
```
Any idea? Thanks

**Comment by lukasfrana** [comment]
I found that this issue is related with vue@2.6.x and it also affects ApolloQuery component. Its content is being rendered twice and the second does not have any scoped slot, which results in error.

**Comment by dominik-bln** [comment]
If seen this briefly and sadly can't remember what fixed it.

Are you using `vue@2.6.x`? Have you tried with the new `v-slot` syntax there.

The only other difference we have is `tag=""` on the `ApolloMutation`, maybe that is an accidental workaround.
