### ISSUE TITLE
Error when using fetchoptions in apolloclient

### ISSUE THREAD

**Issue by paulrostorp** [vuejs/vue-apollo#514]
Hi,
I am running into an error when using fetchoptions in the apolloclient:
`Error sending the query 'QUERYNAME' ServerParseError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)`

When configuring the httplink like this :
`const link = new HttpLink({
  uri: 'http://localhost:4000',
  credentials: 'include',
  fetchOptions: {
    mode: 'no-cors'
  }
});`

Any advice ?

**Comment by hieunguyen336** [comment]
I had same the error.

**Comment by hieunguyen336** [comment]
> Hi,
> I am running into an error when using fetchoptions in the apolloclient:
> `Error sending the query 'QUERYNAME' ServerParseError: Unexpected end of JSON input at JSON.parse (<anonymous>)`
> 
> When configuring the httplink like this :
> `const link = new HttpLink({ uri: 'http://localhost:4000', credentials: 'include', fetchOptions: { mode: 'no-cors' } });`
> 
> Any advice ?

I solved it, it's belong to the stage of parse in the AST of GraphQL. I suggest should use the GraphiQL or GraphQL Playground to the queries or mutations etc before you run it in the code. Coz, the both of them can help you to detect the syntax. Good luck!
