### ISSUE TITLE
Uncaught (in promise) Error

### ISSUE THREAD

**Issue by mehmetpolat** [vuejs/vue-apollo#519]
hi friends, my apollo code are as follows;

`apollo: {
            wallets: {
                query: checkAddress,
                variables : {
                    address : "adress_name"
                },
                 result({data, loading, networkStatus}) {
                    console.log(data);

                },
                update(data) {
                    return data
                },
                error(e) {
                     console.log(e);
                }
            }
        }`

My problem is that If  address field in variables tag is correct, no problem. But if wrong, I am getting an error like `Uncaught (in promise) Error` at console. Where am I doing wrong. How can I handle my task.I am waiting your valuable answers.Thanks in advance.

**Comment by ydfzgyj** [comment]
It's a graphql Error, you should handle it during creating apollo client with `apollo-link-error`.
