### ISSUE TITLE
$apollo undefined in SSR

### ISSUE THREAD

**Issue by dsanders11** [vuejs/vue-apollo#852]
**Describe the bug**
After c3b840c368d50cb21f7410119a50443596baa537, any usage of `$apollo` (such as `$apollo.queries.<query>.loading`) in templates will result in an error. This is because `$apollo` will now be null.

@Akryum, is it possible to retain the memory leak fix in c3b840c368d50cb21f7410119a50443596baa537 by only destroying `$apollo`, without it being set to `null`?

**Versions**
vue: 2.6.10
vue-apollo: 3.0.0

**Comment by sebmor** [comment]
+1 Came here to post exactly this

**Comment by Akryum** [comment]
Test: https://github.com/vuejs/vue-apollo/blob/81b8a4894ab3ebf84f2de030f290604e1e7c26c7/packages/test-ssr/tests/e2e/specs/apollo-ssr.js#L13-L17
