### ISSUE TITLE
Authorization Header via `getAuth`

### ISSUE THREAD

**Issue by CVANCGCG** [vuejs/vue-apollo#865]
**Is your feature request related to a problem? Please describe.**
Yes, it's a problem but this may have to do with my lack of understanding or choice of implementation details.

Our team is using Vue Apollo as the interface to our Apollo Graph QL server. For authentication, we are using Okta's (OIDC/OAuth) PKCE workflow for single sign on. What I have attempted but fail to do is to find a way to use the vue-apollo client's `getAuth` callback to set the Authorization token to: `BEARER <access-token-sting>. 

**Describe the solution you'd like**
I'd like to use the `getAuth` callback to override the default with the HTTP Authorization header as follows so that our Apollo API gateway can extract just the string and do its own validation and authorization.
Authorization: `BEARER <access-token-sting>. 

const defaultOptions: ApolloClientClientConfig<object> = {
  httpEndpoint, ...
  // Override the way the Authorization header is set
  getAuth: (tokenName: string) => { 
           Vue.prototype.$auth.getAccessToken()
                    .then((accessToken: string) => {
                       return `Bearer ${accessToken}`
         })
 }

As you can see the OKTA Auth library code (at: https://github.com/okta/okta-oidc-js/blob/master/packages/okta-vue/src/Auth.js) is written with async/await and returns a promise. What I have failed to do is to find a way for the the `getAuth` to wait for the OKTA's getAcessToken() promise to resolve. Is there a way to force the Apollo Client to wait for the promise to resolve?

**Describe alternatives you've considered**
It appears as though I am stuck because I don't know how to integrate an async function I need  by Okta to work with `getAuth` which expects a synchronous response.

1. As I've written the code, I always return the promise but it's ignored by the Apollo Client. I've tried setting the AUTH_TOKEN as follows:
const AUTH_TOKEN = 'okta-token-storage'
This is problematic, because OKTA's token is an object not a string and contains too much info that I don't want to pass through as HTTP headers. It contains name, email, profile and other related info required by the Vue app but is not allowed per our InfoSec team.
2. I've tried adding `async` to convert the signature of the function
  getAuth: async (tokenName: string) => { 
This also falils
**Additional context**

**Comment by paulpdaniels** [comment]
@CVANCGCG usually I do this sort of thing through the `Apollo-link-context`, which definitely supports async/await. Is there a reason you can’t do that?

**Comment by CVANCGCG** [comment]
Hi Paul, thank you for the prompt response. Is this the best reference issue to go over for [Apollo-link-context](https://github.com/apollographql/apollo-client/issues/4990). I ask because we have code that uses these initializers and can't find where to insert the reference code in relation to it.

```// Call this in the Vue app file
export function createProvider(options = {}) {
  // Create apollo client
  const { apolloClient, wsClient } = createApolloClient({
    ...defaultOptions,
    ...options,
    cache: new InMemoryCache({
      fragmentMatcher,
    }),
  })

  // Create vue apollo provider
  const apolloProvider = new VueApollo({
    defaultClient: apolloClient,
    defaultOptions: {
      $query: {
        // fetchPolicy: 'cache-and-network',
      },
    },
    errorHandler(error) {
      // eslint-disable-next-line no-console
      console.log(
        '%cError',
        'background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;',
        error.message
      )
    },
  })
  apolloProvider['wsClient'] = wsClient
```

**Comment by Booligoosh** [comment]
For @CVANCGCG and anyone else who's ended up here from Google etc, this is how I got it to work…

1. Create a new auth link:
```javascript
import { setContext } from "apollo-link-context";

const authLink = setContext(async (_, { headers }) => {
  // Use your async token function here:
  const token = await getToken();
  // Return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : ""
    }
  };
});
```
2. Add it to your `defaultOptions` object:
```javascript
const defaultOptions = {
  // ...
  link: authLink
  // ...
}
```
Hope that makes sense, let me know if you have any questions!

**Comment by wiemann** [comment]
@Booligoosh I have the same link setup for auth tokens but they don't get sent to the websocket endopoint, only http. Any ideas on how to fix that?

**Comment by Booligoosh** [comment]
@wiemann Not sure sorry, I only use an HTTP endpoint in my app.

**Comment by mskg** [comment]
> @wiemann Not sure sorry, I only use an HTTP endpoint in my app.

Websoka

> @Booligoosh I have the same link setup for auth tokens but they don't get sent to the websocket endopoint, only http. Any ideas on how to fix that?

Websockets don't support headers in browsers. You have to do the configuration via WebSocketLink.

**Comment by CVANCGCG** [comment]
@Booligoosh , thanks so much for the response and apologize for the delayed response. You are absolutely correct that the setContext() callback is called per request and is working for me.
