### ISSUE TITLE
Memory Optimization - Cached data copied in every component?

### ISSUE THREAD

**Issue by sve-odoo** [vuejs/vue-apollo#884]
I have a vue-apollo app running in production for about a year and I love it.

I have a question regarding memory optimization.

Upon startup, my app loads a big chunk of data via a GraphQL Query.
The result of this query is used in many components, each time using the `apollo `option and a related reactive property in the `data` option.

My question is:
Is the data copied as many times as the number of components using this query?

And if yes, is it something that should be fixed in the vue-apollo package, or is there a way to optimize my app's memory usage?

Thanks!

**Comment by Akryum** [comment]
vue-apollo doesn't copy data. This should probably asked on Apollo Client project directly.

**Comment by sve-odoo** [comment]
Thanks.

I'm not 100% sure I understand correctly. Do you confirm that in this simple example component that you wrote: https://github.com/Akryum/vueconf-2017-demo/blob/master/src/components/Blog1.vue

`posts` doesn't actually hold data in the component instance, but is only a proxy to the Apollo cache?

**Comment by Akryum** [comment]
It directly uses whathever is in the ApolloQueryResult object returned by the ObservableQuery from Apollo Client.

**Comment by sve-odoo** [comment]
I managed to reduce the memory footprint of my app by declaring the _heavy_ query only on my root component, and accessing it from the children component with **$root** instead of re-declaring it each time.

To get a bit more context, in case anyone has a better solution for me, this is what I had:
- a heavy query "allRecords"
- a vuex variable "currentRecordId"

And in many of my components I have the computed property "currentRecord" (something like `allRecords.find(r => r.id === currentRecordId)` )

I hoped to create a vuex getter for this, but vuex cannot access apollo queries.
So I re-created this computed property in all components, with the query re-declared in each component to be able to access allRecords and compute currentRecord.

**Comment by sve-odoo** [comment]
In other words, unless I'm mistaken, I don't think that the current best practice (of declaring a query on every component that needs it) is scalable.
I'll continue my tests.
