### ISSUE TITLE
The new vue composition api should have an option for a default error handler

### ISSUE THREAD

**Issue by pietdevries94** [vuejs/vue-apollo#885]
The options api has a way to give a default errorhandler when building the provider. It would be really helpful if there could be a way to add this to the composition api.

Biggest reasons for this are less verbose code and always having some handling, instead of being able to forget to implement anything.

**Comment by Akryum** [comment]
Use `error-link`.

**Comment by pietdevries94** [comment]
That is not sufficient. Error-link always goes off, while I want to be able to overwrite the default behavior.

**Comment by Akryum** [comment]
You can control if the error-link does something with the context.

**Comment by Akryum** [comment]
You can also create an higher-order version of `useQuery` for example, with your own defaults for every parameter.

**Comment by pietdevries94** [comment]
I completely overlooked the context. Thanks a lot! The higher order function is also a great suggestion! Thanks for your answer.
