### ISSUE TITLE
How to update httpLink ?

### ISSUE THREAD

**Issue by ad34** [vuejs/vue-apollo#886]
**Is your feature request related to a problem? Please describe.**

I use vue-apollo on a project where there is differents envrionneemnt for preproduction.
We have a global environnement selector in a top bar, so when it's changed, I would like to update the httpLink , but I have no idea how to update this

**Describe the solution you'd like**

something like this.apollo.updateHttpLink(newURL)

**Describe alternatives you've considered**

I tried to dig into this.$apolloProvider.defaultClient but didn't manage to find a way to fix our isse

**Comment by Akryum** [comment]
Use the context to manipulate http-link.
[Docs here](https://www.apollographql.com/docs/link/links/http/#context)

**Comment by ad34** [comment]
thanks it works fine :)
