### ISSUE TITLE
Error when using the useMutation function

### ISSUE THREAD

**Issue by farcasmihai91** [vuejs/vue-apollo#888]
**Describe the bug**
I am getting this error when trying to use the new `useMutation` function:

```
TypeError: Cannot read property '$root' of null
    at getAppTracking (loadingTracking.js?b1f0:5)
    at getCurrentTracking (loadingTracking.js?b1f0:25)
    at track (loadingTracking.js?b1f0:50)
    at Object.trackMutation (loadingTracking.js?b1f0:70)
    at useMutation (useMutation.js?89f9:59)
    at useCreatePractitionerMutation (practitioner.ts?1d55:81)
    at useRegisterPractitionerMutation$ (practitioner.ts?1d55:87)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:271)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
```

**To Reproduce**

Also, I know this should have been fixed in `alpha.4`, but for me the `data` is still of type `any`.
here is part of my code: 

```
const CREATE_PRACTITIONER = gql`
  mutation createPractitioner($input: CreatePractitionerInput!) {
    createPractitioner(input: $input) {
      clientMutationId
    }
  }
`;
export const useCreatePractitionerMutation = () => {
  return useMutation<
    CreatePractitionerMutation,
    CreatePractitionerMutationVariables
  >(CREATE_PRACTITIONER);
};

export const useRegisterPractitionerMutation = async (practitioner ) => {
 const variables: CreatePractitionerMutationVariables = { input: { practitioner } };

  const { loading, mutate, onError } = useCreatePractitionerMutation();
  const { data } = await mutate(variables, {
    awaitRefetchQueries: true,
    fetchPolicy: "network-only",
    refetchQueries: ["practitionerByPractitionerId"]
  });

  onError(err => useNotifyApolloError(err, errorMessages.FETCH_DATA_ERROR));

  return { loading, data };
};
```

**Expected behavior**

Since this is a brand new API I am not even sure that I am using it the correct way. Any help is appreciated!
**Versions**
"vue": "2.6.11" / "2.6.10"
"@vue/apollo-composable": "^4.0.0-alpha.4",
"@vue/apollo-util": "^4.0.0-alpha.2",
"@vue/composition-api": "^0.3.4",
"apollo-client": "^2.6.8",

Thanks!

**Comment by Vahelnir** [comment]
I guess i also have this issue with:
```js
useMutation(EDIT_PUBLICATION_MUTATION, { variables });
```

Stacktrace: 
```
TypeError: Cannot read property '$root' of null
    at getAppTracking (loadingTracking.js?b1f0:5)
    at getCurrentTracking (loadingTracking.js?b1f0:25)
    at track (loadingTracking.js?b1f0:50)
    at Object.trackMutation (loadingTracking.js?b1f0:70)
    at useMutation (useMutation.js?89f9:59)
    at editPublication (usePublication.ts?e0a6:36)
    at edit (VM2695 FeedbackForm.vue:75)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)
```

"vue": "^2.6.11",
"@vue/apollo-composable": "^4.0.0-alpha.5",
"@vue/composition-api": "^0.3.4",

**Comment by farcasmihai91** [comment]
Updated packages, deleted the `node_modules` folder and re-installed everything, problem still persists.

```
"vue": "2.6.11""
"@vue/apollo-composable": "^4.0.0-alpha.6"
"@vue/apollo-util": "^4.0.0-alpha.6"
"@vue/composition-api": "^0.3.4"
"apollo-client": "^2.6.8"
```

**Comment by Vahelnir** [comment]
How are you using the mutation in your component ?

**Comment by farcasmihai91** [comment]
```js
const submit = async (
      practitioner: Pick<
        PractitionerInput,
        | "practitionerId"
        | "familyName"
        | "givenName"
        | "birthDate"
        | "administrativeGenderId"
      >,
      contactPoint: Pick<ContactPointInput, "value">
    ) => {
      try {
        console.log(practitionerFormRef);
        await practitionerFormRef?.value?.validate();
        await contactPointFormRef?.value?.validate();
      } catch (error) {
        notifyError(errorMessages.FORM_VALIDATION);
        return;
      }

      try {
        loadingMutation.value = true;
        const { loading, data } = await useRegisterPractitionerMutation(
          practitioner,
          contactPoint
        );
        console.log(loading);
        console.log(data);
      } catch (error) {
        console.log(error);
      }
    };
```

**Comment by Vahelnir** [comment]
https://v4.apollo.vuejs.org/api/use-mutation.html
The `useMutation()` function returns a `mutate` function, which is the one you should use in your submit function.
So you should do something like this:
```js
setup(props, { root }) {
  const { loading, mutate } = await useRegisterPractitionerMutation(practitioner);
  const submit = async (myData: any) => {
      try {
        const fetchResult = await mutate(practitioner);
        console.log(fetchResult);
      } catch (error) {
        console.log(error);
      }
    };
  return {
    loading,
    submit
  };
}
```

**Comment by farcasmihai91** [comment]
Thank you!

Well I just call it from another async function because I want my business logic and validation logic in one place. Should not make any difference really, I do the same with the queries and only mutations seem to have the same issue.

Nevertheless I tried using it like above but I still have the issue.

**Comment by Vahelnir** [comment]
Queries are working as expected because you call your function in your `setup()`. Queries starts as soon as you call the `useQuery()` function because you need the result as soon as possible to populate your component.
Whereas mutations are frequently (if not always) called when the user does something.
The thing is that if we call the `useMutation()` function in the event handler, it can not get the current component context. That's why we have to call `useMutation()` in the setup to prepare the mutation , and then use the `mutate()` function that we got from it.

Can you show me what you tried ?

**Comment by farcasmihai91** [comment]
Thanks for the explanation!
Indeed you can't call the `useMutation` function within an `async` method. Calling it inside the `setup()` and outside my `async submit()` function worked.

I will have to see how I can get around this issue since I want to have a single createX, updateY method for each entity since I do not want each component to re-implement it's own validation and business logic.... 

Closing for now since it's clear what's happening and I don't think it's a bug within the library.

**Comment by rebz** [comment]
@farcasmihai91 - did you find a workaround? I have the same problem... I have composition functions that make a store and use the `useMutation` inside of it, but these composition functions are not invoked until a component calls them from `setup()`... yet I am getting the same error.

**Comment by Vahelnir** [comment]
@rebz The `useMutation()` function should be called directly inside the setup function.

It should be something like that
```js
export default defineComponent({
  setup() {
    // here the call to useMutation can resolve your component
    const { mutate } = useMutation(yourGqlMutation);
    function doSomething() {
      return mutate(args)
    }

	return { doSomething }
  }
})
```

and not 
```js
export default defineComponent({
  setup() {
    function doSomething() {
	  // if you call your useMutation here, the function can't resolve your component 
      const { mutate } = useMutation(yourGqlMutation);
      return mutate(args)
    }

	return { doSomething }
  }
})
```

**Comment by farcasmihai91** [comment]
@rebz 
Yes, I did manage to extract this sort of logic outside of the setup function once I better understood how Vue 3.0's composition API works.

The nice thing about it is that you can use watch and ref outside of the Vue context (yes, 😎 ), here is an example, `reusable-queries.ts` file:

```ts
export const getXById = (id: Ref<string | undefined>) => {
  const options = ref<UseQueryOptions>({
    enabled: false,
  });
  const variables = ref<XByIdQueryVariables>({
    id: id.value,
  });
  watch(id, () => {
    variables.value.id= id.value;
    options.value.enabled = !!id.value;
  });
  const { loading, result, onError } = useXByIdQuery(variables, options);

  onError((err) => useNotifyApolloError(err, errorMessages.FETCH_DATA_ERROR));

  const x = useResult(result, null, (data) => data.xById);
  return { loading, x};
};
```

Hope it helps!

**Comment by rebz** [comment]
@Vahelnir - I have a `useMutation` in a composition function called `useModelById`.

`useModelById` is used inside of a `createModelStore` composition function.

`createModelStore` is used inside of a `createModelsStore` (loops over models and creates a store for each)

`createModelsStore` is used inside of a larger `createDifferentModelStore`.

`createDifferentModelStore` is provided, via a `setup()` and injected in child components via a `setup()`.

`useMutation` works fine in any composition function I create... it fails to work when I loop over the `createModelStore` composition function.

Even if I wrap every single composition function in a `provideApolloClient` method, `useMutation` cannot find the Apollo Client.

I'll try and create a sandbox demo this weekend to share.

I've got a Vue 2.6 Production app using the Vue Composition Plugin... so that may be part of the problem. So far I have been able to use `useQuery`, `useMutation`, `useLazyQuery` and others OUTSIDE of `setup()`... but for some darn reason this compounding stores method I have is losing access to the Apollo Client.

@farcasmihai91 - Ah, yeah I've done that too... was hoping that perhaps you were doing something different I had not tried. As I said in my statement above I'll work on making a sandbox demo this weekend. Maybe I'm missing something minor... or perhaps I don't understand the reactivity issue when doing a `for` loop on my `createModelStore`.

**Comment by Vahelnir** [comment]
> useMutation works fine in any composition function I create... it fails to work when I loop over the createModelStore composition function.

I am guessing that you are using async tasks somewhere in your `createModelStore()` which makes a call to `useMutation()` after your `setup()` function returns.
I made a sandbox emulating your case the possible error you are having (well, i hope it does).
You can try switching the boolean at Demo.vue:38 !
https://codesandbox.io/s/usemutation-demo-sandbox-hjce9?file=/src/components/Demo.vue

**Comment by rebz** [comment]
@Vahelnir - That is the error... looks close to what I am doing too; though not using an async function. The creating of stores occurs when the user selects a form value; causing a watcher to loop over related data and create a store for each. I started working on a sandbox that mimics my setup, I'll finish it up tomorrow to share.

Appreciate your responses.

**Comment by Vahelnir** [comment]
> The creating of stores occurs when the user selects a form value;

That's exactly the issue. Your stores have to be created in your setup function, but not in any watch, hook or event callback. Once your setup function returns, you cannot call useMutation anymore. Not sure how to provide a better explaination tho since english is not my main language :s

**Comment by rebz** [comment]
@Vahelnir - Your explanation is great. Problem is now I need to think of a new method for creating these composition stores on the fly... 

Thanks!
