### ISSUE TITLE
Apollo composable + typescript issue

### ISSUE THREAD

**Issue by j-tegen** [vuejs/vue-apollo#904]
Hi,

I've just started to look into the new composition api for vue using `@vue/composition-api` and really like the idea of using `@vue/apollo-composable`.

The example in the documentation uses the `setup` method in the root instance instantiation, but when I try this in my main.ts file:
```
new Vue({
  router,
  setup() {
    provide(DefaultApolloClient, apolloClient)
  },
  render: h => h(App),
}).$mount('#app')
```
I get the following errors:
```
Argument of type '{ router: VueRouter; setup(this: void): void; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Types of property 'setup' are incompatible.
    Type '(this: void) => void' is not assignable to type 'SetupFunction<Data, Data>'.
      Type 'void' is not assignable to type 'Data | (() => VNode | null)'.
    14 | Vue.use(VueSessionStorage)
    15 |
  > 16 | new Vue({
       |         ^
    17 |   router,
    18 |   setup() {
    19 |     provide(DefaultApolloClient, apolloClient)
```
Does anyone know what I can do to prevent this? Is there another way to provide the apolloClient and still be able to use the composable functions?

EDIT:
Steps to reproduce:
1. Create vue app with `vue create <name>` (@vue/cli 4.1.2) and configure for ts
2. Add apollo using `vue add apollo`
3. `npm install @vue/composition-api @vue/apollo-composable`
4. Change vue instantiation in `main.ts` to include `setup` method and `provide(DefaultApolloClient, apolloClient)`:
```
import Vue from 'vue'

import { DefaultApolloClient } from '@vue/apollo-composable'
import VueCompositionApi, { provide } from '@vue/composition-api'

import App from './App.vue'
import router from './router'
import { apolloClient } from './vue-apollo'

Vue.config.productionTip = false
Vue.use(VueCompositionApi)

new Vue({
  router,
  setup() {
    provide(DefaultApolloClient, apolloClient)
  },
  render: h => h(App),
}).$mount('#app')
```

**Comment by Akryum** [comment]
Maybe it's an issue with `setup` typing.

**Comment by j-tegen** [comment]
Well, found the answer and now I feel silly!
`setup` can't be void, so all I had to do was to add `return {}`... Thanks for the pointer in the right direction!

**Comment by Sevensidedmarble** [comment]
Might be nice to have a note about this in the official docs. I ran into this too and wouldn't have figured it out were it not for this ticket.
