### ISSUE TITLE
TypeScript vue instance issues when using reactive params

### ISSUE THREAD

**Issue by danielwaltz** [vuejs/vue-apollo#907]
**Describe the bug**
https://apollo.vuejs.org/guide/apollo/queries.html#reactive-parameters

When using reactive params or skipping a query, TypeScript loses access to the current Vue instance when accessing `this` across the entire component.

```js
<script lang="ts">
import Vue from 'vue';
import { ApolloQueryResult } from 'apollo-client';
import ITEM from '@/graphql/queries/Item.graphql';
import { Item } from '@/types/schema';

export default Vue.extend({
  name: 'ApolloTest',
  data() {
    return {
      item: null,
    };
  },
  apollo: {
    item: {
      query: ITEM,
      // Removing 'variables' and 'skip' fixes errors
      variables() {
        return {
          id: this.$route.params.id,
        };
      },
      skip() {
        return !this.$route.params.id;
      },
      // Accessing the Vue instance in the result function works fine
      result(response: ApolloQueryResult<Item>) {
        const { item } = response.data;
        console.log(item);
      },
    },
  },
});
</script>
```

**To Reproduce**
1. Create a test query using reactive variables or skip.
2. Observe type issues when accessing properties on Vue's instance anywhere inside the component.

**Expected behavior**
No type errors when access properties on the Vue instance inside `apollo` param functions.

**Versions**
vue: `2.6.11`
vue-apollo: `3.0.2`
apollo-client: `2.6.8`

**Comment by danielwaltz** [comment]
After doing some more debugging I believe it's actually due to a `vuelidate` mixin interfering. I don't think `vue-apollo` is the issue here, sorry!

**Comment by danielwaltz** [comment]
Although this is closed, I also noticed that adding an explicity return type to these functions helped:

```
apollo: {
  item: {
    query: ITEM,
    variables(): ItemQueryVariables {
      return {
        id: this.$route.params.id,
      };
    },
    skip(): boolean {
      return !this.$route.params.id;
    },
  },
},
```

**Comment by YutaUra** [comment]
Amazing!!

I'm looking for this for an hour...

**Comment by solidevolution** [comment]
@danielwaltz thanks! I missed the return type of "skip" ...
