### ISSUE TITLE
[Translation] Vue Apollo in French 🇫🇷

### ISSUE THREAD

**Issue by sarahdayan** [vuejs/vue-apollo#919]
**Is your feature request related to a problem? Please describe.**

The documentation is currently only in English and Chinese.

**Describe the solution you'd like**

A translation of the documentation in French.

Hey folks! Thanks for the awesome package. I'm willing to contribute to the docs by adding the complete French translation to help the library reach even more people.

**Comment by Akryum** [comment]
👍
