### ISSUE TITLE
multi-query throws "missing attribute on result"

### ISSUE THREAD

**Issue by adarisGmbH** [vuejs/vue-apollo#935]
I'm taking advantage of the fact that GQL allows for several queries to coexist in a single request, like so:
```graphql
query globalsearch($keyword: String!) {  
  crm {
    contacts (filter: { byName: { search: $keyword } })
    {
      items 
      {        
        oid    
        firstName      
      }             
    }
  }

  courseMgmt {
    courses (filter: { byName: { search: $keyword } })
    {
      items 
      {            
        name
        status      
      }             
    }
  }

  sales{  
    salesInvoices(filter: { byKeyword: { search: $keyword }    })
    {
      items { 
        oid
        date
        number
      }
    }
  }    
}
```
This throws an exception named "Missing globalsearch attribute on result". I don't understand why. I explicitly want three independent arrays to be returned from the server in one request. Thoughts?

**Comment by adarisGmbH** [comment]
I just checked the documentation, and my example is explicitly listed as being supported by apollo: 
https://v4.apollo.vuejs.org/guide-composable/query.html#executing-a-query

```gql
query getCatsAndDogs {
  cats {
    id
  }

  dogs {
    id
  }
}
```

This query doesn't contain any attribute named "getCatsAndDogs" either.

**Comment by Akryum** [comment]
Use: `update: data => data`.

**Comment by adarisGmbH** [comment]
@Akryum Thanks a lot, it works!
