### ISSUE TITLE
Why `addSmartQuery` is not recommended?

### ISSUE THREAD

**Issue by alexxiyang** [vuejs/vue-apollo#943]
Based on https://apollo.vuejs.org/api/dollar-apollo.html#methods
It said: `addSmartQuery`: manually add a Smart Query (not recommended).

But why `addSmartQuery` is not recommended? Is there any issue it can lead to?

**Comment by igreench** [comment]
I need to run smart query manually. How can I implement it right way?

Reason of this is absctraction layer between ui and api
