### ISSUE TITLE
Error when use enum

### ISSUE THREAD

**Issue by adrianoresende** [vuejs/vue-apollo#953]
**Describe the bug**
I get an error because `enum`

`Schema type definitions not allowed in queries. Found: "EnumTypeDefinition"`

```js
import queryComponents from '../../graphql/queries/components'

export default {
...
apollo: {
    components: {
      query: queryComponents,
      variables() {
        return {
          type: this.$route.params.type.toUpperCase(),
          slug: this.$route.params.slug
        }
      }
    }
  }
}
```

```graphql
query components($type: Type, $slug: String) {
  components(where: {
    type: $type,
    slug: $slug
  }) {
    title
  }
}

enum Type {
  MARKETING,
  APPLICATION
}
```

What is best the way to use enum?

**Versions**
vue-apollo: ^3.0.3
nuxt: ^2.12.2

**Comment by Akryum** [comment]
The answer is in the error message. `Schema type definitions not allowed in queries.` You can only define types and enums on the graphql schema server-side.

**Comment by adrianoresende** [comment]
> The answer is in the error message. `Schema type definitions not allowed in queries.` You can only define types and enums on the graphql schema server-side.

@Akryum 
I understand what the error said, couldn't you suggest the solution?

If I remove `enum`, the error persist until solve this part `$type: Type`

What is the best way to solve? Convert `String` to `Type` inside query in server-side?
