### ISSUE TITLE
Mismatching childNodes vs. VNodes in Nuxt.js when using Smart Query with Date variable

### ISSUE THREAD

**Issue by sturatcliffe** [vuejs/vue-apollo#960]
**Describe the bug**
In Nuxt.js (specifically using nuxt-apollo module which wraps Vue-Apollo), when using a Smart Query with a Date variable, the following warnings are displayed in the browser console on initial page load:

```
Mismatching childNodes vs. VNodes
```
and
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

This only happens with variables that are dates, e.g:

```
variables: {
  timestamp: new Date()
}
```

**To Reproduce**
1. Create a new Nuxt application
2. Setup a new GraphQL query which uses a Date variable, e.g:

```
query upcomingCourses ($timestamp: timestamptz!) {
  courses(limit: 3, order_by: {startDate: asc, qualification: { title: asc }}, where: {startDate: {_gte: $timestamp}}) {
    id
    qualification {
      title
      slug
      image
    }
    price
    startDate
    endDate
    spacesRemaining
    location {
      addressLine1
      addressLine2
      townCity
      postcode
    }
  }
}
```

3. Consume the query in a Nuxt page component smart query object, e.g:

```
apollo: {
  courses: {
    query,
    variables: {
      timestamp: new Date()
    }     
  }
}
```

4. Start the app, navigate to the page, and see browser console for warnings.

**Expected behavior**
Using Smart Queries with Date variables shouldn't result in cliend/server DOM mismatches on initial page loads.

**Versions**
vue: 2.6.11
vue-apollo: 3.0.3
apollo-client: 2.6.8

**Additional context**
The workaround which I've found is to avoid smart queries when Date variables are required, and fetch initial page data using Nuxt's ```asyncData``` functionality instead, e.g. instead of:

```
apollo: {
  courses: {
    query,
    variables: {
      timestamp: new Date()
    }     
  }
}
```
use
```
async asyncData(context) {
  const { data } = await context.app.apolloProvider.defaultClient.query({
    query,
    variables: {
      timestamp: new Date()
    }
  })

  return {
    courses: data.courses
  }
}
```

However, this isn't desirable as the code isn't nearly as clean, nor does it benefit from the ```subscribeToMore``` functionality available with smart queries, meaning we then have to setup a separate subscription on top of this.

**Comment by Akryum** [comment]
Apollo uses the variables values to match the results from the cache, so by the time your client initiate the same query the date value has changed. Try using the `@connection` directive on your query ([docs](https://www.apollographql.com/docs/react/caching/cache-interaction/#the-connection-directive)).

**Comment by sturatcliffe** [comment]
That does indeed fix the issue, thanks!

I did suspect the value of new Date() on server / client being different was the fundamental cause, but when asyncData worked perfectly, it threw me off. Why would the same query work from asyncData?
