### ISSUE TITLE
Intercepting every queries/mutation requests

### ISSUE THREAD

**Issue by chadwtaylor** [vuejs/vue-apollo#963]
**Is your feature request related to a problem? Please describe.**
Using an example, a Firebase Auth token is only good for one hour. The end-user could stay on one page (eg: videoconferencing) for more than one hour. By then, the Firebase Auth token in the apollo header has expired and the next query or mutation will fail. I have tried to use the middleware to update the token in the header but the end user could just stay on the page and not move between routes therefore the middleware is not called. 

**Describe the solution you'd like**
What I would like is the ability to globally intercept every query/mutation requests. Case in point, the Axios library allows us to intercept every request via `onRequest`. Using an example from my nuxt project:

```es6
// /plugins/axios.js
export default function ({ $axios, $fireAuth }) {
  $axios.onRequest(async config => {
    if ($fireAuth) {
      config.headers.token = await $fireAuth.currentUser.getIdToken()
    }
  }
}
```

**Describe alternatives you've considered**
As mentioned above, I tried the middleware approach but the issue is that the end-user could stay on the same page for hours, therefore we need the ability to intercept every query/mutation requests globally so we can update the headers wherever necessary. 

I've Googled high and low and could not get any solution as close to the solution Axios feasibly provide us with their library.

**Additional context**
If this is already available, I'd love to hear how Apollo queries and mutations can be intercepted. You'd save the day like Superman saves the world from Doomsday! :)

**Comment by Akryum** [comment]
Look at Apollo Links.

**Comment by chadwtaylor** [comment]
Thank you so much @Akryum. I read up on Apollo Links; and my struggle here is grasping the concept of where I can manipulate the `headers` right before it's sent out. If you have any examples or resources that illustrate how one can, for example modify the headers on every request, that would be greatly appreciated. 

Again, thank you for your valuable time.

**Comment by douglasg14b** [comment]
@chadwtaylor Did you every find a good solution? I'm staring at pages of questions on this with fragmented or hand-waved "links" comments, but not getting much that's concrete.

Same use case here, I need to set an auth related header (JWT bearer token). As with JWTs this can expire mid-request or right before a request is sent, meaning the request can fail. I need to preemptively check the token's validity before every request, and if it looks like it should be expired, request a new one before the request continues.
