### ISSUE TITLE
V4 use of queries outside of setup

### ISSUE THREAD

**Issue by Manborough** [vuejs/vue-apollo#970]
Can the functions in vue Apollo V4 be used outside the setup function/a vue component?
It seems like the composition API was designed in part to allow features to be split off into different files, but I can't find a way to do that currently. It throws a VM error if I write a standard query, or an inject error if I try to import the Apollo client for local state management.

**Comment by Akryum** [comment]
You can use the functions from another file inside a component's `setup`. Outside of setup, it won't work.

**Comment by matrunchyk** [comment]
Similar request (I'm using Vue2 though), could we make it possible to instantiate DollarApollo outside the plugin's install function? Can we have it re-export it? I don't use vue-apollo components, but just need `addSmartQuery` in [my vue-oop](https://github.com/matrunchyk/vue-oop). I use a workaround by retrieving $apollo from the `vm`, but this is not the best thing, as I run into race conditions sometimes when the plugin is npm-linked.
