### ISSUE TITLE
Is there a way to manipulate data returned after the query with in query: update: ?

### ISSUE THREAD

**Issue by bizready** [vuejs/vue-apollo#971]
I have following query:

```
enrolledServices: {
      query: gql(listServices),
      variables () {
        let idFilter = this.idFilter(this.userData.enrolledServiceIds);
        console.log('enrolledServices:idFilter', idFilter);
        return {
          filter: {
            or: idFilter
          }
        };
      },
    },
```
```
searchResultServices: {
      query: gql(listServices),
      variables () {
        return {
          filter: {
            or: [
              { name: { contains: this.searchServiceText } },
              { description: { contains: this.searchServiceText } },
              { tags: { contains: this.searchServiceText } }
            ],
          }
        };
      },
      update: data => {
        //before returning data, I need remove user's already enrolled services -> enrolledServices
       return data.listServices.items
      }
    }
```

In the searchResultServices results, I need to remove user who already enrolled services which is part of enrolledServices. Is there a way to access global or outside variables with update: methods scope? It does not take any additional param other than 'data' returned from the query. Both `enrolledServices` and `searchResultServices` reactively used in UI. The only option is to write some yucky filter code in UI before displaying `searchResultServices` ?

**Comment by bbugh** [comment]
Yes, you just need to change your `update` to a regular function instead of an arrow function. Within the arrow function `this` is not the component. Your `variables` function is correct, but `update` is not.

**Comment by bizready** [comment]
Awesome and great catch. Now, I am clear on the arrow function in javascript. Thanks so much @bbugh
