### ISSUE TITLE
[testing][docs] How to mock apollo queries result

### ISSUE THREAD

**Issue by dlumbrer** [vuejs/vue-apollo#989]
**Describe the bug**
There is no information about how to mock the result of a query made with apollo (using $apollo or the 'apollo' provider directly in the component).

**Expected behavior**
I expect to have a guide or an example of mocking apollo result of queries/mutations in order to see the component rendered with the mocked result of the queries and compare with a snapshot.

**Versions**
vue: ^2.6.11 
vue-apollo: ^3.0.3
apollo-client: ^2.6.9

**Additional context**
I went to this part of the guide https://apollo.vuejs.org/guide/testing.html#simple-tests but if I use the setData method for the wrapper, the snapshot generated is empty, not showing me the data.

**Comment by Loremaster** [comment]
@dlumbrer did you find any way to do it?

**Comment by dlumbrer** [comment]
> @dlumbrer did you find any way to do it?

Yes, I found a way to do it putting an await in the setData statement: https://github.com/vuejs/vue-test-utils/issues/1562

**Comment by mikhaylov-ya** [comment]
@dlumbrer 
Still do not clear how to mock apollo provider queried fields in the component. You use setData to set top-level property in the wrapper, I do not see any signs of interacting with Apollo.

Can you please deliver full and clear example how to mock a given query field like "items" here:
```js
apollo: {
  items: {
    query: require("@/graphql/some-query.gql"),
    update({ items }) { return items; },
  }
}
```
